In [2]:
import pandas as pd

In [15]:
data=['Tea','Coffee','Milkshake','Juice','Toast']

df=pd.DataFrame(data,columns=['Breakfast'])
df

   Breakfast
0        Tea
1     Coffee
2  Milkshake
3      Juice
4      Toast

In [14]:
data=[
    {"name":"Adam","age":32},
    {"name":"Chloe","age":33},
    {"name":"Olive","age":21}
]
df=pd.DataFrame(data)
df

    name  age
0   Adam   32
1  Chloe   33
2  Olive   21

In [17]:
data=[
    ["Adam",34],
    ["Chloe",31],
    ["Olive",24]
]
df=pd.DataFrame(data,columns=['name','age'])
df

    name  age
0   Adam   34
1  Chloe   31
2  Olive   24

In [22]:
data ={
    "name":["Adam","Chloe","Olive"],
    "age":[34,21,43]
}

df=pd.DataFrame(data,columns=["Name","Age"])
df

Empty DataFrame
Columns: [Name, Age]
Index: []